### ISSUE TITLE
Error occurred while enabling SurvivalPlus v3.12.0 (Is it up to date?)

### ISSUE THREAD

**Issue by HeyNennMichChris** [ShaneBeeStudios/SurvivalPlus#9]
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Enabling SurvivalPlus v3.12.0
[02:38:18] [Server thread/INFO]: [SurvivalPlus] new config.yml created
[02:38:18] [Server thread/INFO]: [SurvivalPlus] config.yml loaded
[02:38:18] [Server thread/INFO]: [SurvivalPlus] New lang_EN.yml created
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Resource pack enabled
[02:38:18] [Server thread/INFO]: [SurvivalPlus] New data.yml created
[02:38:18] [Server thread/INFO]: [SurvivalPlus] PlaceholderAPI placeholders enabled
[02:38:18] [Server thread/INFO]: [SurvivalPlus] NoPos implemented - F3 coordinates are disabled!
[02:38:18] [Server thread/ERROR]: Error occurred while enabling SurvivalPlus v3.12.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.removeRecipe(Lorg/bukkit/NamespacedKey;)Z
	at tk.shanebee.survival.managers.RecipeManager.removeRecipeByKey(RecipeManager.java:1217) ~[?:?]
	at tk.shanebee.survival.managers.RecipeManager.removeRecipes(RecipeManager.java:1107) ~[?:?]
	at tk.shanebee.survival.managers.RecipeManager.loadCustomRecipes(RecipeManager.java:41) ~[?:?]
	at tk.shanebee.survival.Survival.onEnable(Survival.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.2.jar:git-Paper-77]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:291) ~[patched_1.15.2.jar:git-Paper-77]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-77]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Disabling SurvivalPlus v3.12.0
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Shutting down
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Unloading player data for 0 players
[02:38:18] [Server thread/INFO]: [SurvivalPlus] Successfully disabled

**Comment by HeyNennMichChris** [comment]
https://pastebin.com/xdqLerrB

**Comment by HeyNennMichChris** [comment]
how can i fix it?

**Comment by HeyNennMichChris** [comment]
i have deactivate the NoPos, but the error ist always there
https://pastebin.com/QYd7E3L7

**Comment by HeyNennMichChris** [comment]
update the paper version :D
